### ISSUE TITLE
I have a problem running this logger for ionic 3 /angular4

### ISSUE THREAD

**Issue by 23aryan** [Ritzlgrmft/ionic-logging-service#13]
in my app.module.ts I cant import LoggingServiceModule, and when I try to run my app I get the following error:
No provider for LoggingService! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for LoggingService!

I'm using the angular 4.4.4, and ionic-logging-service 3.1.0,

Am I missing something? 
please let me know how I can resolve this issue.

Thanks

**Comment by Ritzlgrmft** [comment]
Which error do you get when you try to import the `LoggingServiceModule`?
And which version of Ionic are you using? Older than 3.9.0?
