### ISSUE TITLE
erroneous code example in readme.md

### ISSUE THREAD

**Issue by achimwessling** [Ritzlgrmft/ionic-logging-service#16]
Your code example in 'readme.md' does NOT work for me.

Mine has to look this way:

```
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    AppRoutingModule,
    BrowserModule,
    IonicModule.forRoot()
  ],
  providers: [
    LoggingService,
    SplashScreen,
    StatusBar,
    {
      provide: RouteReuseStrategy,
      useClass: IonicRouteStrategy
    },
    {
      deps: [LoggingService],
      multi: true,
      provide: APP_INITIALIZER,
      useFactory: configureLogging
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

```

I only get working code if I do add `LoggingService` inside the `providers`. I do not believe this is specific to my project.

**Comment by Ritzlgrmft** [comment]
It seems you missed the `import` of `LoggingServiceModule`? With this `import`, I didn't need to add the `LoggingService` to the `providers`.

**Comment by draoZA** [comment]
Hi, I'm also struggling with example code. Logger works but I don't get the environment variables read. Manual log level set later works. What is the APP_INITIALIZER? 

code below:

import { LoggingService, LoggingServiceModule} from 'ionic-logging-service';
...
export function configureLogging(loggingService: LoggingService): () => void {
  return () => loggingService.configure(environment.logging);
}
...
@NgModule({
  ...
  imports: [
    ...
    LoggingServiceModule,
   ...
    {
      deps: [LoggingService],
      multi: true,
      provide: APP_INITIALIZER,
      useFactory: configureLogging
    }

**Comment by draoZA** [comment]
Ok, APP_Initializer is a known issue with ionic 4
https://github.com/ionic-team/ionic/issues/17993

**Comment by Ritzlgrmft** [comment]
I do not think that your problem is related to the ionic issue.

Please have a look at https://github.com/Ritzlgrmft/ionic-logging-viewer.
