### ISSUE TITLE
minimum log level INFO

### ISSUE THREAD

**Issue by draoZA** [Ritzlgrmft/ionic-logging-service#18]
I don't get debug messages. Minimum is INFO. Below example will only show warn & info statement. But if I set log level to WARN only warn will be displayed. So info is correctly filtered out

this.logger.setLogLevel(LogLevel.ALL);
    this.logger.warn(methodName, 'dummy warn');
    this.logger.info(methodName, 'dummy info');
    this.logger.debug(methodName, 'dummy debug');
    this.logger.trace(methodName, 'dummy trace');

**Comment by Ritzlgrmft** [comment]
Which appender are you using? Probably `BrowserConsoleAppender` in Chrome. In this case please have a look at https://github.com/Ritzlgrmft/ionic-logging-service/issues/4#issuecomment-341889027.

Beside this, in https://github.com/Ritzlgrmft/ionic-logging-viewer you could find a working app, also using DEBUG logs.
