### ISSUE TITLE
How can I change the time format to ISO date format?

### ISSUE THREAD

**Issue by ramonjsantiago** [Ritzlgrmft/ionic-logging-service#21]
Is this an attribute that needs to be added to something like this;
    "logging": {
        "logLevels": [
            {
                "loggerName": "root",
                "logLevel": "INFO"
            }
        ]
    }

**Comment by Ritzlgrmft** [comment]
The AjaxAppender is using [log4javascript's JsonLayout](http://log4javascript.org/docs/manual.html#jsonlayout). If you want to have another layout, you need to 
- implement an own layout
- assign it to the AjaxAppender

If you need more detailed advise, just let me know.
