### ISSUE TITLE
Original location/line number from where log is written is lost, 

### ISSUE THREAD

**Issue by voodark** [Ritzlgrmft/ionic-logging-service#23]
Original location/line number from where log is written is lost, is there a way to preserve that?
when we use console.log it will give line number and file name, and when you click on the link it will take you to exact location. But now with this, there is no clue where it came from. we need to search and find

**Comment by Ritzlgrmft** [comment]
I'm afraid, this isn't as easy as it sounds, see also my comments to #17.
