### ISSUE TITLE
How to remove or clear stored logs?

### ISSUE THREAD

**Issue by pixelone** [Ritzlgrmft/ionic-logging-service#27]
I implemented a simple bug report section and after submission want to clear the logs.  How can I do that?  

I see here 
https://ritzlgrmft.github.io/ionic-logging-service//service/injectables/LoggingService.html#removeLogMessagesFromLocalStorage 

But this method doesn't seem present in your current version.  I am using Ionic 5 and Angular 9. 

Appreciate all your hard work and time on this.

**Comment by Ritzlgrmft** [comment]
Please upgrade to version 10

**Comment by pixelone** [comment]
Thanks.  Where is version 10 though?  https://github.com/Ritzlgrmft/ionic-logging-service/releases

**Comment by Ritzlgrmft** [comment]
You are right, I forgot to create the release on GitHub. Now it's there.

On npm, the release 10.0.0 is already published since 11 days...
