### ISSUE TITLE
Custom Appender

### ISSUE THREAD

**Issue by pentabarf** [Ritzlgrmft/ionic-logging-service#33]
Hello,

Is it possible to make my own appender? Do you have any template for this?
log4javascript provides some infos for custom appenders but i can not figure out how to use it in an ionic project.

**Comment by Ritzlgrmft** [comment]
Please checkout https://github.com/Ritzlgrmft/ionic-logging-service/blob/master/projects/ionic-logging-service/src/lib/local-storage-appender.model.ts. This is an example of an `Appender` implementation. You have to implement mainly `append()` and `toString()`.

To use it just call:
```
log4javascript.getRootLogger().addAppender(yourAppender);
```
