### ISSUE TITLE
Config option to allow AjaxAppender withCredentials=true

### ISSUE THREAD

**Issue by marracuene** [Ritzlgrmft/ionic-logging-service#34]
The underlying `log4javascript.AjaxAppender` which is used by `ionic-logging-service.AjaxAppender`, appears to support a second constructor parameter which allows `withCredentials` to be set to true.   See https://github.com/Ritzlgrmft/log4javascript/blob/master/js/log4javascript_uncompressed.js :1948 

However `ionic-logging-service.AjaxAppender` does not offer a configuration option to allow this to be set to true.

I could get around this by implementing a new "AuthenticatedAjaxAppender', along the lines you describe in https://github.com/Ritzlgrmft/ionic-logging-service/issues/33 , however it seems like it would be a simple thing to include in the core library.

The use case is that we don't want abuse of an unsecured log endpoint which receives POSTs from an Ionic app, across the public internet.

**Comment by Ritzlgrmft** [comment]
implemented with [release 10.1.0](https://github.com/Ritzlgrmft/ionic-logging-service/releases/tag/v10.1.0).

@marracuene: Thanks for suggesting it!
