### ISSUE TITLE
Angular 11 Support

### ISSUE THREAD

**Issue by pixelone** [Ritzlgrmft/ionic-logging-service#37]
Possible this can be updated for Angular 11 support? 

`Package "ionic-logging-service" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "11.2.7").`

Thanks again for all your hard work.

**Comment by Ritzlgrmft** [comment]
It's definitely on my list. But it will probably take some days.

BTW: from my experience, the package is also working in an Angular 11 application.

**Comment by Ritzlgrmft** [comment]
solved with [version 12.0.0](https://github.com/Ritzlgrmft/ionic-logging-service/releases/tag/v12.0.0)
