### ISSUE TITLE
Calling configureLogging in app.module.ts

### ISSUE THREAD

**Issue by Remonell** [Ritzlgrmft/ionic-logging-service#44]
Hi,

first of all, thank you for your hard work. I followed your tutorial and got stuck at this point. Basically I want the user to choose the threshold via GUI. So I adapted the configureLogging method like so:

```
export function configureLogging(loggingService: LoggingService, config:LoggingServiceConfiguration): () => void {
  return () => loggingService.configure(config);
}
```

When I call configureLogging what would you suggest to fill in as a parameter for the loggingService? 
I am fairly new to TypeScript and this is maybe a more TypeScript related question.
As far as I understand the useFactory in the NgModule section in app.module.ts creates an instance of loggingService. So I am not sure how I would do this without the useFactory part.
Hopefully you can give me some hints in the right direction.

**Comment by Ritzlgrmft** [comment]
ou should remove the `config` parameter from `configureLogging`. This method is called from Angular at application start. Instead you can calculate your `config` object inside the method (in my example, I just used `environment.logging` for that).

If the user wants to change the threshold later, you can call `configure()` again, but you have to test if it works with every appender as it should. I never tested this.

Another option could be what I implemented in `ionic-logging-viewer-app/src/app/home/home.page.ts`. There I change some logging configuration on the fly.
