### ISSUE TITLE
localStorageAppender problem

### ISSUE THREAD

**Issue by iadimitriu** [Ritzlgrmft/ionic-logging-service#5]
Hi,
I found a problem in "src/logging.service.ts", lines 78:83, there seems to be a wrong condition.
Also, can you provide an example of setting.json? I tried to change settings to save the log in local storage but without any success.

**Comment by Ritzlgrmft** [comment]
What do you mean with "wrong condition"? Could you please explain it in more detail?

An example of `settings.json` is:

```json
{
  "logLevels": [
    {
      "loggerName": "root",
      "logLevel": "DEBUG"
    }
  ],
  "localStorageAppender": {
    "localStorageKey": "logInLocalStorage",
    "threshold": "INFO"
  }
}
```

**Comment by vlinde** [comment]
`if (typeof configuration === "undefined") {
			configuration = this.configurationService.getValue("logging");
		}
 if (typeof configuration === "undefined") {
			configuration = {};
		}`
Second condition will overwrite the first one.

**Comment by Ritzlgrmft** [comment]
@vlinde: I think everything is fine:

1. If there was no `configuration` passed, it tries to get the configuration from the `configurationService` (which could return `undefined` as well if there is no `logging` configuration).
1. If there is still no configuration (means the `configurationService` returned `undefined`), `configuration` is set to an empty object.
