### ISSUE TITLE
Include @angular/core: >=12.0.0 in the peerDependencies (Angular 15 support)

### ISSUE THREAD

**Issue by Acousticdesk** [Ritzlgrmft/ionic-logging-service#71]
In the [npm documentation](https://www.npmjs.com/package/ionic-logging-service), it is said that the dependencies are the same as in the Ionic Angular v6.1.9.

However, the **@ionic/angular package** has the "@angular/core: >=12.0.0" mentioned in the peerDependencies.
At the same time, **ionic-logging-service** has "@angular/core: ^14.0.0".

### Why this is important?
The teams who use the package, can't upgrade to Angular 15 due to the inconsistencies in the peerDependencies.

**Comment by Ritzlgrmft** [comment]
I published a new version (16.0.0) which has now a dependency to @angular/core in version ^15.0.0. With this version, you should be able to upgrade to Angular 15.
