### ISSUE TITLE
What happens when app is offline?

### ISSUE THREAD

**Issue by sakonn** [Ritzlgrmft/ionic-logging-service#83]
Hello, 
thanks for the nice project. We would like to incorporate that into our ionic app. I am just thinking about the reliability of log delivery. If I understand the implementation correctly the logs are appended to `AjaxAppender` and are right pushed to the server (after the batch threshold is reached). What happens when the log is created locally but the delivery fails? 
Either due to a missing internet connection on the device or due to the server error? Are the logs stored somewhere locally and tried to re-upload them? I have gone through both appenders implementations and don't see such a feature. Is it possible to add that functionality? 

This is a crucial requirement for us because we want to use logs to debug the uploading of data from the ionic app to the server so the connection outage can happen during the process.

**Comment by Ritzlgrmft** [comment]
I understand your need, however, the `AjaxAppender` is taking from the underlying `log4javascript`, and it does not provide such an offline functionality.

But it shouldn't be too hard to write such a functionality by your own. Just implement your own `Appender`. As an example, you can check [local-storage-appender](https://github.com/Ritzlgrmft/ionic-logging-service/blob/main/projects/ionic-logging-service/src/lib/local-storage-appender.model.ts).

I hope this helps a little bit.
